TRUNCATE TABLE ORDER_TRACKER RESTART IDENTITY;
TRUNCATE TABLE ERROR_TRACKER RESTART IDENTITY;

ALTER SEQUENCE ORDER_TRACKER RESTART WITH 1;

DROP TABLE ORDER_TRACKER;

-- Remove column
ALTER TABLE ORDER_TRACKER DROP COLUMN BUY;

CREATE TABLE TRADE_BOT (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    symbol VARCHAR(255),
    createdDate DATE,
    taskId VARCHAR(255),
    quoteOrderQty INT,
    cycleMaxOrders INT,
    orderStep DOUBLE,
    description VARCHAR(255),
    initialDelay INT,
    delay INT,
    timeUnit INT
);


CREATE TABLE ORDER_TRACKER (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    sell BOOLEAN,
    buyPrice DECIMAL(14,8),
    sellPrice DECIMAL(14,8),
    profit DECIMAL(14,8),
    buyDate TIMESTAMP,
    sellDate TIMESTAMP,
    buyOrderId BIGINT,
    sellOrderId BIGINT,
    tradebot_id BIGINT,
    FOREIGN KEY (tradebot_id) REFERENCES TRADE_BOT(id)
);

CREATE TABLE ERROR_TRACKER (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    errorTimestamp TIMESTAMP,
    errorMessage VARCHAR(255),
    acknowledged BOOLEAN,
    tradebot_id BIGINT,
    FOREIGN KEY (tradebot_id) REFERENCES TRADE_BOT(id)
);
